### PR TITLE
Prepare vaadin 18.0-snapshot

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/1499)

### CODE REVIEW

**Review by manolo — CHANGES_REQUESTED** [review]
shouldn't  we have all dependencies of flow-components  set in this PR? 

> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1499#-:-MFjmJzF3oroxPFeuu58:bvk1nb7)* status: 0 of 17 files reviewed, all discussions resolved

**Review by ZheSun88 — COMMENTED** [review]
nothing can stop us from doing those. let us wait for the validation then

> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1499#-:-MFnOHkX5TczdoGtxFZG:bagtvvo)* status: 0 of 18 files reviewed, all discussions resolved

**Review by ZheSun88 — COMMENTED** [review]
now, we need to merge this one and have the 18.0-SNAPSHOT deployed before merging this PR

> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1499#-:-MFnVEZC6ZaDV5gyjoWh:boovpbc)* status: 0 of 18 files reviewed, all discussions resolved

**Review by manolo — APPROVED** [review]

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 16 of 18 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1499#-:-MGECM258U5YYW8Y2kc7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
