### PR TITLE
Move version properties to parent pom

### PR DESCRIPTION
**Pull request by alvarezguille**
Versions should be used both in vaadin-core and vaadin-bom
vaadin-core should not use vaadin-bom as it is part of it

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/157)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Can you elaborate a bit how it's helping javadocs to be published?
Before that it was rather convenient to release snapshots with the setup.

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/157#-:-LC-4AUM3_vLC52ImE5G:bhyzzff)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/157)*

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/157#-LC-4pGD07MlDl4FdMVu:-LC-4pGD07MlDl4FdMVv:b-3m8zfr) (no related file):*
Let's not merge this yet

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/157)*

**Comment by alvarezguille** [comment]
It should still be possible to set properties to snapshot, they're just moved to parent project.
But looks like we don't need this after all.
I still think it's a bit strange that `vaadin-core` is part of and uses `vaadin-bom`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/157#-:-LC-75_Z2bysL5ivu7Ui:b-i2hz15)*

**Pull request closed without merging**
