### PR TITLE
Add versions.json + generator script (#2)

### PR DESCRIPTION
**Pull request by ripla**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/181)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Looks really cool.

Two ideas for future updates to discuss: 
* generate the same pom.xml but with snapshot versions (only if trivial to implement or if we continue to use "incorrect" prerelease versioning pattern, which renders us unable to use `versions-maven-plugin`)
* remove current `vaadin-bom.xml`, gitignore it and always generate it with the script to avoid situations when someone changes the one in the project but forgets about the template. Alternatively, somehow verify both for mismatches.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LD6jyjI7yKU_pMugugq:-LD6jyjJ6Ys_iTiqNBTO:bp7jg6l) (no related file):*
Should we also care about transitive web components' dependencies such as the one updated in https://github.com/vaadin/platform/pull/178 ?

---

*[versions.json, line 1 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oYyn09_FHpTBa7so:-LD6oYyn09_FHpTBa7sp:b-pnodpv) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/versions.json#L1)):*
> ```JSON
> {
> ```

Might it be better to put this file into `scripts/generator`?

---

*[scripts/generator/generate.js, line 9 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oHvH62I9kJ0enVXZ:-LD6oHvH62I9kJ0enVX_:b-su1gqo) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/generate.js#L9)):*
> ```JavaScript
> 
> if(!argv['platform']) {
>     console.log('Specify platform version as \'-platform=11.12.13\'');
> ```

Double dash here and lower, for versions param?

---

*[scripts/generator/generate.js, line 23 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6qzvg75sqHQlgKSW4:-LD6qzvg75sqHQlgKSW5:b-jwnhr0) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/generate.js#L23)):*
> ```JavaScript
> const inputVersions = require(versionsFileName);
> 
> const coreBowerTemplateFileName = path.resolve('./templates/template-vaadin-core-bower.json');
> ```

Not sure if it we need to verify that all those paths exist, but might be a good idea.
Up to you.

---

*[scripts/generator/README.md, line 6 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6kUW70FoEeWtB_6cX:-LD6kUW70FoEeWtB_6cY:b-xkjm4u) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/README.md#L6)):*
> ```
> -platform
> ```

Should it be `--platform` (double dash)? 

---

*[scripts/generator/src/creator.js, line 22 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6taNT1bajflIBk1f1:-LD6taNT1bajflIBk1f2:b-exebf8) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/src/creator.js#L22)):*
> ```
> bowerTemplate
> ```

mavenTemplate?

---

*[scripts/generator/src/creator.js, line 29 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6u7NgB3mv_1onr_FZ:-LD6u7NgB3mv_1onr_F_:bynm1vs) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/src/creator.js#L29)):*
> ```JavaScript
>     let mavenDeps = '';
>     for (let dependencyName in allVersions) {
>         const dependency = allVersions[dependencyName];
> ```

In ES2017 you can use `for...or` and get both key and value when iterating, but it's really minor.

---

*[scripts/generator/templates/template-vaadin-bower.json, line 6 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6sPpaA0tRQXx71HRc:-LD6sPpaA0tRQXx71HRd:b-q12zky) ([raw file](https://github.com/vaadin/platform/blob/cf6c845d8802f8fea5f5953136e26ee9cf4bc007/scripts/generator/templates/template-vaadin-bower.json#L6)):*
> ```JSON
>   "homepage": "https://github.com/vaadin/vaadin",
>   "authors": [
>     "Artur Signell <artur@vaadin.com>"
> ```

Might it make sense to replace it with `Vaadin Ltd` here also?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181#-:-LD6oqBtAbNwCqP8EqHL:bjffk6h)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LDAvkbu45Vra_LFHtxj:-LDAvkbu45Vra_LFHtxk:bpmwosa) (no related file):*
https://github.com/vaadin/platform/pull/171

This PR had changed the pom a bit (removed one dependency, bumped the versions), I guess, we should update some things in this PR also.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181)*

**Comment by ripla** [comment]
What does using snapshots mean exactly? Given the flag `--useSnapshots` the script should modify each java version to the format `<major>.<minor>-SNAPSHOT`?

Good idea about the `vaadin-bom.xml`, I'll remove it. Should the main readme include instructions for this script, as after the removal I guess just doing `git clone && mvn package` wont work anymore?

---

Review status: 7 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LD6jyjI7yKU_pMugugq:-LDBR3USA_Y4a_70G5J5:b-axnx3o) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Should we also care about transitive web components' dependencies such as the one updated in https://github.com/vaadin/platform/pull/178 ?
</blockquote></details>

Good question, I don't know. I think we can put anything into the `versions.json` that makes sense for us. Maybe a good qualifier would be that if it's updated often, include it in the versions file. Should I add `vaadin-overlay`, and is there something else I should add?

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LDAvkbu45Vra_LFHtxj:-LDBS2Fh3H7rYydx-3GC:b-8k7bkl) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

https://github.com/vaadin/platform/pull/171

This PR had changed the pom a bit (removed one dependency, bumped the versions), I guess, we should update some things in this PR also.
</blockquote></details>

Yeah I'll update.

---

*[scripts/generator/generate.js, line 9 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oHvH62I9kJ0enVXZ:-LDBSdaQB-6ZP4h-gCfT:bspwe26) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/generate.js#L9)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Double dash here and lower, for versions param?
</blockquote></details>

Urgh. Fix.

---

*[scripts/generator/generate.js, line 23 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6qzvg75sqHQlgKSW4:-LDFYU0B9t2UBzNL4W_C:b4unvbu) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/generate.js#L23)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Not sure if it we need to verify that all those paths exist, but might be a good idea.
Up to you.
</blockquote></details>

I _think_ the methods afterwards throw exceptions when the paths cannot be found. IMHO not a issue right now, we can fix later.

---

*[scripts/generator/README.md, line 6 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6kUW70FoEeWtB_6cX:-LDBWpJD65N3LpKjkwF9:bt2vr1b) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/README.md#L6)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> -platform
> ```

Should it be `--platform` (double dash)? 
</blockquote></details>

Fixed.

---

*[scripts/generator/src/creator.js, line 22 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6taNT1bajflIBk1f1:-LDBSpr923Df6yckUP9G:b-886gsx) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/src/creator.js#L22)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> bowerTemplate
> ```

mavenTemplate?
</blockquote></details>

Fixed

---

*[scripts/generator/src/creator.js, line 29 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6u7NgB3mv_1onr_FZ:-LDFYejL5TivGYQnfWQ-:btg456g) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/src/creator.js#L29)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

In ES2017 you can use `for...or` and get both key and value when iterating, but it's really minor.
</blockquote></details>

Done, it's a bit cleaner.

---

*[scripts/generator/templates/template-vaadin-bower.json, line 6 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6sPpaA0tRQXx71HRc:-LDBXGHU9NSFf9x9eJ67:bb6un1j) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/templates/template-vaadin-bower.json#L6)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Might it make sense to replace it with `Vaadin Ltd` here also?
</blockquote></details>

Done

---

*[versions.json, line 1 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oYyn09_FHpTBa7so:-LDBST7c8n-lKFYjne6b:bi92gun) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/versions.json#L1)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Might it be better to put this file into `scripts/generator`?
</blockquote></details>

Can do. The reason I put it in the root was to make it more prominent, as it is *the* way versions should be updated. I'll move it under `scripts/generator`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181#-:-LDBROER8AmhYGGq9tAS:bdjo4tj)*

**Comment by SomeoneToIgnore** [comment]
> Given the flag --useSnapshots the script should modify each java version to the format <major>.<minor>-SNAPSHOT?

Yeah, sounds reasonable to me.

> Should the main readme include instructions for this script, as after the removal I guess just doing git clone && mvn package wont work anymore?

Looks like a nice idea, sure. Also, travis.yml (that's what causes build fails now for the PR) and bender CI jobs (I can adjust those after this PR is merged) should be updated to handle those changes.

---

Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LD6jyjI7yKU_pMugugq:-LDH-uPC-nuHaHX28D8E:b-cia9ex) (no related file):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Good question, I don't know. I think we can put anything into the `versions.json` that makes sense for us. Maybe a good qualifier would be that if it's updated often, include it in the versions file. Should I add `vaadin-overlay`, and is there something else I should add?
</blockquote></details>

No idea, let's leave everything as is now and sort this out when really needed.

---

*[scripts/generator/generate.js, line 9 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oHvH62I9kJ0enVXZ:-LDH0BDU4sbLZsI3bnvn:bv786df) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/generate.js#L9)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Urgh. Fix.
</blockquote></details>

Well, now it's a triple dash here :) 
But the second one is fixed, good job!

---

*[scripts/generator/generate.js, line 23 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6qzvg75sqHQlgKSW4:-LDH0KT4D6S7ZSyS-slR:b-dv7wre) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/generate.js#L23)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

I _think_ the methods afterwards throw exceptions when the paths cannot be found. IMHO not a issue right now, we can fix later.
</blockquote></details>

Sure, as I've said, not sure about it at all.

---

*[versions.json, line 1 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oYyn09_FHpTBa7so:-LDH0SDM6nHlnZTi7WGZ:btojbfq) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/versions.json#L1)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

Can do. The reason I put it in the root was to make it more prominent, as it is *the* way versions should be updated. I'll move it under `scripts/generator`.
</blockquote></details>

Great.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181#-:-LDH-euK3Qi0FV2jtCIB:b2o5guq)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LDLln4vEW6s9LT-ZYpu:-LDLln4w9fn2cRVhz9AZ:b-sos2pt) (no related file):*
https://github.com/vaadin/platform/pull/183

Another PR is in, so more version updates needed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181)*

**Comment by ripla** [comment]
How would the builds know which version to build? I would suggest to keep the BOM in the version control for now.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LDLln4vEW6s9LT-ZYpu:-LDvo0je5syoj4bTM52E:b-896fix) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

https://github.com/vaadin/platform/pull/183

Another PR is in, so more version updates needed.
</blockquote></details>

Done.

---

*[scripts/generator/generate.js, line 9 at r1](https://reviewable.io/reviews/vaadin/platform/181#-LD6oHvH62I9kJ0enVXZ:-LDHdu8R6UHY8zJTh6Zw:b-1z398h) ([raw file](https://github.com/vaadin/platform/blob/13b12541d19063b636bac2122156824f5e2ec5fa/scripts/generator/generate.js#L9)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Well, now it's a triple dash here :) 
But the second one is fixed, good job!
</blockquote></details>

:man_facepalming: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181#-:-LDvnsho96jJcFLsZZyC:bn80gbn)*

**Comment by SomeoneToIgnore** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LEJ6nWY5y28WE10QCwD:-LEJ6nWZ9YzrOf67Jd_I:b8bd7s) (no related file):*
I've pushed some version updates to a template and updated Travis script to build the bom for us.

The generator script has a minor bug that corrupts the pom.xml though: 
`<iron.list.version>1.0.0.rc1</iron.list.version>` is generated in the properties, but in the dependencies it's referenced as 
```
<dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-iron-list-flow</artifactId>
                <version>${vaadin.iron.list.version}</version>
            </dependency>
```
So we need not to add the `vaadin.` prefix in this case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181)*

**Comment by ripla** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/181#-LEJ6nWY5y28WE10QCwD:-LEJxr3Z2p6SV1gM1Rjv:b-896fix) (no related file):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

I've pushed some version updates to a template and updated Travis script to build the bom for us.

The generator script has a minor bug that corrupts the pom.xml though: 
`<iron.list.version>1.0.0.rc1</iron.list.version>` is generated in the properties, but in the dependencies it's referenced as 
```
<dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-iron-list-flow</artifactId>
                <version>${vaadin.iron.list.version}</version>
            </dependency>
```
So we need not to add the `vaadin.` prefix in this case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/181#-:-LEKCs172DD2uPhJxNHZ:bnfp4nl)*

**Pull request merged**
