### PR TITLE
Bump CE to 3.0.0 stable

### PR DESCRIPTION
**Pull request by pekam**

### CODE REVIEW

**Comment by ZheSun88** [comment]
Is there something we should test on platform level? a smoke test is enough.

**Comment by pekam** [comment]
I thought that the platform team is writing a smoke test for CE..? But if that's a misunderstanding, we can of course create one.

**Comment by ZheSun88** [comment]
we are indeed starting to check the missing tests for modules in platform, so if it is not big burden to add it, can you help?

**Comment by pekam** [comment]
Yes. :+1:  I've created a ticket about it for myself in our backlog and will probably work on that on Monday.

I guess it shouldn't block this PR though? CE is already there as a dependency and this PR is just bumping the version.

**Review by manolo — APPROVED** [review]

**Pull request merged**
