### PR TITLE
Update usage-statistics and dev-mode-detector

### PR DESCRIPTION
**Pull request by web-padawan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/688)

### CODE REVIEW

**Comment by alvarezguille** [comment]
FYI I think these are also pinned in flow-component-base

**Comment by tulioag** [comment]
Needs to be updated in flow component base. https://github.com/vaadin/flow-component-base/blob/master/pom.xml#L550-L560

**Comment by web-padawan** [comment]
Submitted vaadin/flow-component-base#150

**Comment by web-padawan** [comment]
Closing in favor of #699 which incorporated the changes from this PR.

**Pull request closed without merging**
