### PR TITLE
Define repositories in parent instead of in each module

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/175)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 57 at r1](https://reviewable.io/reviews/vaadin/platform/175#-LD0q47_DdrH0fOJNBsg:-LD0q47a7Tv7Mb0d5_PV:b-f2flcm) ([raw file](https://github.com/vaadin/platform/blob/50370f0b89c3cdf7a24589e1b4474743b7d54323/pom.xml#L57)):*
> ```XML
>     </repositories>
>     <pluginRepositories>
>         <pluginRepository>
> ```

No plugins snapshots?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/175)*

**Comment by qtdzz** [comment]
Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 58 at r1](https://reviewable.io/reviews/vaadin/platform/175#-LD0q6Y1CfEKl6ANm2f7:-LD0q6Y1CfEKl6ANm2f8:b-sjag22) ([raw file](https://github.com/vaadin/platform/blob/50370f0b89c3cdf7a24589e1b4474743b7d54323/pom.xml#L58)):*
> ```XML
>     <pluginRepositories>
>         <pluginRepository>
>             <id>vaadin-pre-relase</id>
> ```

it is a typo?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/175)*

**Comment by Artur-** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 57 at r1](https://reviewable.io/reviews/vaadin/platform/175#-LD0q47_DdrH0fOJNBsg:-LD144Je2d7TNWY8HHZ4:b-896fix) ([raw file](https://github.com/vaadin/platform/blob/50370f0b89c3cdf7a24589e1b4474743b7d54323/pom.xml#L57)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

No plugins snapshots?
</blockquote></details>

Done.

---

*[pom.xml, line 58 at r1](https://reviewable.io/reviews/vaadin/platform/175#-LD0q6Y1CfEKl6ANm2f7:-LD1444IBSs1E9we8srh:b-896fix) ([raw file](https://github.com/vaadin/platform/blob/50370f0b89c3cdf7a24589e1b4474743b7d54323/pom.xml#L58)):*
<details><summary><i>Previously, qtdzz (Tien Nguyen) wrote…</i></summary><blockquote>

it is a typo?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/175)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/175#-:-LD1B8Zj76qpXyakqRIu:bnfp4nl)*

**Pull request merged**
