### PR TITLE
Add serialization test (temporary ignored)

### PR DESCRIPTION
**Pull request by elmot**
Partial fix for #173

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/176)

### CODE REVIEW

**Comment by ripla** [comment]
It's a platform level requirement, but then again products themselves know best how to test this.

**Comment by Artur-** [comment]
I do not think the platform wants to know how the individual products work, e.g. TestBench/Designer/... classes do not need to be serializable while most of Flow and all component API must be

**Comment by ripla** [comment]
@Artur- fine by me. @elmot can you please move the PR to the relevant Flow repo? Thanks.

**Comment by elmot** [comment]
There is a huge pile of repositories, and no shared place for test code.  Is it possible to have abstract test class somewhere and put subclasses with their own whitelists per repo?

**Comment by elmot** [comment]
There is a place already

**Pull request closed without merging**
