### PR TITLE
Changing the structure of test modules and adding tests for OSGi

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
Fixes https://github.com/vaadin/flow/issues/4658

This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/353)

### CODE REVIEW

**Comment by tulioag** [comment]
@mehdi-vaadin The build is failing. Could you take a look?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project platform-tests: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/[secure]/platform/[secure]-platform-test/platform-tests/src/main/java/com/[secure]/platform/test/ComponentsView.java:[231,14] cannot find symbol
[ERROR]   symbol:   class Entity
[ERROR]   location: class com.[secure].platform.test.ComponentsView
[ERROR] /home/travis/build/[secure]/platform/[secure]-platform-test/platform-tests/src/main/java/com/[secure]/platform/test/ComponentsView.java:[231,40] cannot find symbol
[ERROR]   symbol:   class Entity
[ERROR]   location: class com.[secure].platform.test.ComponentsView
[ERROR] /home/travis/build/[secure]/platform/[secure]-platform-test/platform-tests/src/main/java/com/[secure]/platform/test/ComponentsView.java:[232,26] cannot find symbol
[ERROR]   symbol:   class Entity
[ERROR]   location: class com.[secure].platform.test.ComponentsView
[ERROR] -> [Help 1]
```

**Comment by mehdi-vaadin** [comment]
@elmot @tulioag Would you please review the new commits?

**Comment by mehdi-vaadin** [comment]
@qtdzz Great. Thank you. :)

**Comment by mehdi-vaadin** [comment]
This PR is closed since the issue will be fixed in another PR https://github.com/vaadin/platform/pull/479

**Pull request closed without merging**
