### PR TITLE
Update bom template

### PR DESCRIPTION
**Pull request by qtdzz**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/215)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @qtdzz)

---

*[scripts/generator/templates/template-vaadin-bom.xml, line 89 at r1](https://reviewable.io/reviews/vaadin/platform/215#-LFqxFPx-PK8NrZlHbxc:-LFqxFPx-PK8NrZlHbxd:bkyw8zk) ([raw file](https://github.com/vaadin/platform/blob/93da6629b438811720c1cc52810a7b2254fa5205/scripts/generator/templates/template-vaadin-bom.xml#L89)):*
> ```
> ${project.version}
> ```

`project.version` or `vaadin.spring.boot.starter.version`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/215)*

**Comment by qtdzz** [comment]
Review status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @qtdzz)

---

*[scripts/generator/templates/template-vaadin-bom.xml, line 89 at r1](https://reviewable.io/reviews/vaadin/platform/215#-LFqxFPx-PK8NrZlHbxc:-LFqxPUL9Gd63Cb2DWom:b55gkcd) ([raw file](https://github.com/vaadin/platform/blob/93da6629b438811720c1cc52810a7b2254fa5205/scripts/generator/templates/template-vaadin-bom.xml#L89)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> ```
> ${project.version}
> ```

`project.version` or `vaadin.spring.boot.starter.version`?
</blockquote></details>

It should be `project.version`. The generator will use SNAPSHOT version anyway in final build, then the `mvn versions:set` will pick the release version. The problem is if the generator uses the release version, vaadin-platform-parent:%release-version% is not found, it is still SNAPSHOT until we versions:set https://github.com/vaadin/platform/blob/master/pom.xml#L12

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/215)*

**Comment by alvarezguille** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/215#-:-LFqzyXfBMZ7n33-36f6:bnfp4nl)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/215)*

**Pull request merged**
