### PR TITLE
Add template modules

### PR DESCRIPTION
**Pull request by denis-anisimov**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/1552)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Modules should be also added to bom template with version.

**Review by manolo — APPROVED** [review]

**Review by manolo — CHANGES_REQUESTED** [review]
Seems that this needs more changes.
```
$ mvn install $VAADIN_OPTS -DskipTests
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.[secure]:flow-lit-template:jar is missing. @ com.[secure]:[secure]-core:[unknown-version], /home/travis/build/[secure]/platform/[secure]-core/pom.xml, line 40, column 21
[ERROR] 'dependencies.dependency.version' for com.[secure]:flow-polymer-template:jar is missing. @ com.[secure]:[secure]-core:[unknown-version], /home/travis/build/[secure]/platform/[secure]-core/pom.xml, line 44, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
```

**Comment by ZheSun88** [comment]
I have added the template module to scripts, as the bom will be generated there.

**Review by ZheSun88 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1552#-:-MIYZtOl8joPL_puKi5u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
