### PR TITLE
Add spring-boot-starter to bom

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/210)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @Artur-)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/210)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed, all discussions resolved (waiting on @SomeoneToIgnore)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/210#-:-LFR5Jx34nFbk27RzXNU:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/210)*

**Comment by Artur-** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[versions.json, line 9 at r1](https://reviewable.io/reviews/vaadin/platform/210#-LFR42_E-CKvuo5K8rsa:-LFR58Ay7puSWFzNVrlp:b-896fix) ([raw file](https://github.com/vaadin/platform/blob/f441d7d4e95765a1b910d4d4a842dd86c0dd0e95/versions.json#L9)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Please also edit the template file: https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-bom.xml

If you find this confusing, please also edit `README.md` or any other file and add the instructions on how to change the bom.
</blockquote></details>

Done.

---

*[versions.json, line 11 at r1](https://reviewable.io/reviews/vaadin/platform/210#-LFR4O1c1f4XGuAsPoJl:-LFR5VcHCc7_1t9cwwNA:bb6un1j) ([raw file](https://github.com/vaadin/platform/blob/f441d7d4e95765a1b910d4d4a842dd86c0dd0e95/versions.json#L11)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
> ····
> ```

We don't really need trailing whitespaces here, do we?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/210)*

**Pull request merged**
