### PR TITLE
Initial version of platform readme

### LINKED ISSUE #154: Add readme
Create a platform specific readme. The readme should describe what the platform is, what it contains and link to https://github.com/vaadin/vaadin + vaadin.com. 

Contents should be described as a table:
* Flow
* Flow components
* Testbench
* Designer

### PR DESCRIPTION
**Pull request by ripla**
Add a readme for the platform repo that contains the information from https://vaadin.com/platform in a different format. Fixes #154

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/168)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/platform/168#-LCbp7Mc8HF2C-Pu8FZD:-LCbp7Mc8HF2C-Pu8FZE:b-dhqe2j) (no related file):*
What's the benefits of having the version numbers here?
If versions need to be updated when updating vaadin-bom pom this makes it harder to update. 
In most cases what readme will show is not what's included in last platform.

Is it possible to guide users to check release notes for versions info?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/168)*

**Comment by ripla** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/platform/168#-LCbp7Mc8HF2C-Pu8FZD:-LCcP5Pt1xwCikqMeuMc:b-r64gt) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

What's the benefits of having the version numbers here?
If versions need to be updated when updating vaadin-bom pom this makes it harder to update. 
In most cases what readme will show is not what's included in last platform.

Is it possible to guide users to check release notes for versions info?



</blockquote></details>

#FFS. I'm removing the version numbers for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/168)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/platform/168#-LCbp7Mc8HF2C-Pu8FZD:-LCcYuBb-8skRkLbhoZf:bvxttav) (no related file):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

#FFS. I'm removing the version numbers for now.
</blockquote></details>

FFS FTW

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/168)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/platform/168)*

**Pull request merged**
