### PR TITLE
Generate vaadin-spring-bom

### LINKED ISSUE #243: Split BOM
Split the platform BOM into two parts

#### Spring BOM
* Flow + components
* Pro (inc. TB with old Selenium)
* No WebJars
* No SLF4J
* Not compatible with enforcer

#### Vaadin BOM
* Includes Spring BOM
* WebJars
* TB with new Selenium
* SLF4J
* Compatible with enforcer

### PR DESCRIPTION
**Pull request by alvarezguille**
BOM has been split into vaadin-spring-bom and vaadin-bom
vaadin-bom includes vaadin-spring-bom
vaadin-spring-bom has versions only for vaadin artifacts

Fixes #243 

Builds should be adjusted as `.travis.yml` was after merging this

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/248)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
___
*[scripts/generator/templates/template-vaadin-bom.xml, line 72 at r3](https://reviewable.io/reviews/vaadin/platform/248#-LIyVTgEEqcnxJ7zQr9d:-LIyVTgEEqcnxJ7zQr9e:bbgq2wj) ([raw file](https://github.com/vaadin/platform/blob/d5a34499de529dfe75c424864285a303213efa50/scripts/generator/templates/template-vaadin-bom.xml#L72)):*
> ```
>             
> ```


Just a note: we need to double check those before the release and possibly bump those to new versions.

**Comment by alvarezguille** [comment]
___
*[scripts/generator/templates/template-vaadin-bom.xml, line 72 at r3](https://reviewable.io/reviews/vaadin/platform/248#-LIyVTgEEqcnxJ7zQr9d:-LIyfzR36fGDVR2AsuL5:bslhzpf) ([raw file](https://github.com/vaadin/platform/blob/d5a34499de529dfe75c424864285a303213efa50/scripts/generator/templates/template-vaadin-bom.xml#L72)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

> ```
>             
> ```


Just a note: we need to double check those before the release and possibly bump those to new versions.
</blockquote></details>

yes, we need to make these match the version used by the flow-component-base used by the components when updating components and/or when releasing

**Comment by SomeoneToIgnore** [comment]
___
*[scripts/generator/templates/template-vaadin-bom.xml, line 72 at r3](https://reviewable.io/reviews/vaadin/platform/248#-LIyVTgEEqcnxJ7zQr9d:-LIygUrA5XxA65pudefa:b8lc3g6) ([raw file](https://github.com/vaadin/platform/blob/d5a34499de529dfe75c424864285a303213efa50/scripts/generator/templates/template-vaadin-bom.xml#L72)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

yes, we need to make these match the version used by the flow-component-base used by the components when updating components and/or when releasing
</blockquote></details>

In theory, this also can be done by the node script at some point :)

**Comment by alvarezguille** [comment]
___
*[.travis.yml, line 16 at r1](https://reviewable.io/reviews/vaadin/platform/248#-LIyQkbc2TJsLsSTFsKE:-LIyxNhmB2SFsHN7pFeG:bogg4nx) ([raw file](https://github.com/vaadin/platform/blob/cb6fed3ea8ee06f720e5fea0ce827961b01c9438/.travis.yml#L16)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Optional: What do you think of extracting the generation code into a script in the `scripts` directory so that everyone can run a single command instead of 4 now?
</blockquote></details>

Created `scripts/generateBoms.sh` we can add one like this in each branch it will make release and snapshot builds reusable. The only drawback is that it has the major.minor-snapshot hardcoded so we need to update it when jumping to a new major.
I'll create a new PR for 10.0 branch

**Pull request merged**
