### PR TITLE
Change npm releases to use ^ instead of exact versions

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/platform/518)

### CODE REVIEW

**Comment by ripla** [comment]
This is for #515

**Comment by ripla** [comment]
Not sure about this. What if we used the `npmVersion` field instead?

**Comment by Artur-** [comment]
> Not sure about this. What if we used the `npmVersion` field instead?

Wouldn't this mean duplicating every version and just put `^` in front of it?

**Comment by ripla** [comment]
Yes, that's the downside. But it would also allow us to use different versions for Bower and NPM.

**Comment by Artur-** [comment]
> Yes, that's the downside. But it would also allow us to use different versions for Bower and NPM.

I am not sure when you would want that but still `npmVersion` is not going anywhere. This PR just prefixes all versions with `^` in `package.json` so you *can* use the same version for Bower and npm

**Pull request merged**
