### PR TITLE
Update to latest license checker (1.4.0)

### PR DESCRIPTION
**Pull request by mcollovati**

### CODE REVIEW

**Review by Artur- — CHANGES_REQUESTED** [review]
We cannot do this right now. They way it currently works will stop commercial components from working when offline, with no way to make them work. 

Also this update should never go into 23.0

**Comment by mcollovati** [comment]
Sorry, my bad. The PR was mean for master, not for 23.0, but I modified the file on wrong branch.
Is it ok to apply change on master or the above blocker is still valid?

**Comment by Artur-** [comment]
We need a 1.4.1

**Comment by ZheSun88** [comment]
okay, i will close this PR. 

when the 1.4.1 come to platform?

**Comment by Artur-** [comment]
This is for 1.4.1 https://github.com/vaadin/flow/pull/13670 in Flow

**Comment by ZheSun88** [comment]
great. thanks.. 

so after this PR, we can release license checker 1.4.1. and flow 23.1.0.beta1.

**Pull request closed without merging**
