### PR TITLE
chore: Delete shrinkwrap

### PR DESCRIPTION
**Pull request by Artur-**
For https://github.com/vaadin/flow/issues/13008

### CODE REVIEW

**Comment by ZheSun88** [comment]
In order to remove shirinkwrap totally, there are still things missing from this PR:

- remove the shrinkwrap generation file. ([this](https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-core-shrinkwrap-package.json) and [this](https://github.com/vaadin/platform/blob/master/scripts/generator/templates/template-vaadin-shrinkwrap-package.json))
- remove the shrinkwrap profile ([this](https://github.com/vaadin/platform/blob/master/vaadin-core/pom.xml#L361...L413) and [this](https://github.com/vaadin/platform/blob/master/vaadin/pom.xml#L214..L265))
- remove shrink version calculation ([here](https://github.com/vaadin/platform/blob/master/vaadin/pom.xml#L113..L134) and [here](https://github.com/vaadin/platform/blob/master/vaadin-core/pom.xml#L243..L264))

- then modify release steps to skip shrinkwrap updated and npm package publish

**Comment by manolo** [comment]
Should it be removed as well for other flow releases? v22 v14?  if not we need to keep conditional release process in TC

**Review by manolo — APPROVED** [review]

**Comment by Artur-** [comment]
>Should it be removed as well for other platform versions? v22 v14?
While we might want to remove it, we should first do it only for V23 and figure out potential issues.

**Comment by manolo** [comment]
Let's add conditions to release process, right now.

**Comment by ZheSun88** [comment]
I will update the release steps.

**Pull request merged**
